#!/bin/bash
git config --global user.name 'derekgliwa'
git config --global user.email 'dgliwa7bhs@gmail.com'
git config --global alias.amend 'commit --amend --no-edit'
git config --global alias.co 'checkout'
git config --global alias.d 'diff'
git config --global alias.dc 'diff --cached'
git config --global alias.lol 'log --oneline'
git config --global alias.st 'status'
